Crie uma função que encontre o maior valor entre 3 números imputados pelo usuário.


In [20]:
def maior(x,y,z):
    if (x > y and x > z):
        print(x)
    elif (y > x and y > z):
        print(y)  
    elif (z> x and z > y): 
        print(z)

maior(100,500,300)        

500


Crie uma função que identifique se duas ou mais palavras inseridas pelo usuário são anagramas.



In [9]:
def anagrama(s1,s2):
    lista = list(s2)

    pos1 = 0
    OK = True

    while pos1 < len(s1) and OK:
        pos2 = 0
        encontrado = False
        while pos2 < len(lista) and not encontrado:
            if s1[pos1] == lista[pos2]:
                encontrado = True
            else:
                pos2 = pos2 + 1

        if encontrado:
            lista[pos2] = None
        else:
            aindaOK = False

        pos1 = pos1 + 1

    return OK


print(anagrama('ananana','nanana'))


True



Crie uma função que retorne a contagem de consoantes e vogais de uma palavra imputada pelo usuário.

In [5]:
def conta_vogais(string):
    string = string.lower() # para que a comparação não seja sensível a maiuscula/minuscula
    result = {}
    vogais = 'aeiou'
    for i in vogais:
        if i in string:
            result[i] = string.count(i)
    return result

print(conta_vogais('olaaa'))

{'a': 3, 'o': 1}


7)	Crie uma lista com os 100 mil primeiros números naturais na sequência (i.e., de 1 à 100000). Salve esta lista em um objeto com nome cem_mil_lista. Inicie então uma lista vazia chamada numeros_pares. A partir da lista cem_mil_lista, salve todos os valores pares na lista numeros_pares. Resolva este exercício de duas formas: a primeira utilizando um loop com o for e a segunda com list comprehension. Compare o tempo de execução das duas.
* Para comparar o tempo de execução, insira na primeira linha da célula %%time.


In [67]:
%%time 

cem_mil_lista = list(range(1,100000))
numeros_pares=[]

for pares in cem_mil_lista:
    if pares % 2 == 0:
        numeros_pares.append(pares)

#print(numeros_pares)
      
    



CPU times: total: 0 ns
Wall time: 12 ms


In [70]:
%%time 

cem_mil_lista = list(range(1,100000))
numeros_pares=[pares for pares in cem_mil_lista if pares % 2 == 0]
#print(numeros_pares)
      




CPU times: total: 15.6 ms
Wall time: 8.98 ms


9)	Escreva um programa em Python para encontrar os números que são divisíveis por 7 e múltiplos de 5, entre 1500 e 2700 (ambos incluídos). Em outras palavras, combine o que você aprendeu de loop e condicional para criar uma lista de valores que atendam às condições exigidas

In [79]:
numeros = list(range(1500,2700))

div2 = []

def divisiveis (numero):
    for div in numero:
        if div % 5 ==0 and  div % 7 == 0:
            div2.append(div)
    return div2


#divisiveis(numeros)


10)	Escreva um programa Python para construir o padrão a seguir, usando um número de loop aninhado. Ir para o editor
Saída esperada:
1
22
333
4444
55555
666666
7777777
88888888
999999999


In [64]:
numero = int(input('Coloque o numero'))

i = 0
for i in range(1,numero+1):
    for j in range(1, i+1):
        print(i, end='')
        
    print()    

1
22
333
4444
55555
666666
7777777
88888888


11)	Escreva um programa em Python para verificar se um alfabeto é uma vogal ou uma consoante. Ir para o editor
Saída esperada:
Insira uma letra do alfabeto: m
m é uma consoante.


In [106]:
letra = str(input('Insira uma letra do alfabeto'))
vogais ='aeiou'
if letra in vogais:
    print (letra, 'é uma vogal' )
else:
    print( letra,'é uma consoante')

s é uma consoante


In [12]:
13)	Crie um array com 10 números no formato float. Converta-os para o formato inteiro.

SyntaxError: unmatched ')' (3782794895.py, line 1)

In [20]:
import numpy as np
listafloat = np.array([1.00, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0], dtype= float)

np.result_type(listafloat)

listaint= np.array([listafloat], dtype=int)
np.result_type(listaint)

dtype('int32')

14)	Converta o array abaixo para o formato booleano.
a = np.array([1,0,1],[1,1,1],[0,0,0])



In [27]:
a = np.array([[1,0,1],[1,1,1],[0,0,0]], dtype= bool)

print(a)

[[ True False  True]
 [ True  True  True]
 [False False False]]


15)	Empilhe horizontalmente os arrays abaixo.
a = np.array([10,20,15],[0,0,20])
b = np.array([15,7,3],[5,5,8])



In [43]:
a = np.array([[10,20,15],[0,0,20]])
b = np.array([[15,7,3],[5,5,8]])

print(np.concatenate([a,b], axis = 1))


[[10 20 15 15  7  3]
 [ 0  0 20  5  5  8]]


16)	Empilhe verticalmente os arrays do exercício15.

In [44]:
a = np.array([[10,20,15],[0,0,20]])
b = np.array([[15,7,3],[5,5,8]])

print(np.concatenate([a,b], axis = 0))

[[10 20 15]
 [ 0  0 20]
 [15  7  3]
 [ 5  5  8]]


17)	Gere uma lista de números inteiros que vão de 0 a 100, de 2 em 2, e, na sequência, converta essa lista em um array.

In [46]:
lista =np.arange(0,100,2)

lista =np.array([lista])
lista

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
        64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94,
        96, 98]])

18)	Gere uma lista de valores que vão de 5 a 10 de 0.5 em 0.5.

In [47]:
lista = np.arange(5,10,0.5)

lista


array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

19)	Crie um array 3x3 cujos valores seguem uma distribuição normal.

In [80]:
lista = np.random.standard_t([1,1,1],[3,3])

lista

array([[-0.44070144, -0.82611822, -0.33809854],
       [-0.6820577 , -0.11453541,  2.60302589],
       [-1.96759763,  3.86149524,  1.95242578]])